# crea una imagen de nombre    : dockerizingdjango_web
#

FROM nginx
MAINTAINER Franz A. Lopez Choque
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN rm /etc/nginx/conf.d/default.conf
ADD configs/sites-enabled/ /etc/nginx/conf.d
