# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('school_type', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expires', models.CharField(default=b'-1', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=255)),
                ('fb_first_name', models.CharField(max_length=255)),
                ('fb_last_name', models.CharField(max_length=255)),
                ('fb_email', models.EmailField(max_length=255)),
                ('fb_birthday', models.DateField()),
                ('fb_name', models.CharField(max_length=255)),
                ('fb_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettoken.School')),
                ('fb_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettoken.Location')),
                ('fb_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettoken.TokenInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
