# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(default=b'vacio', max_length=255)),
                ('location_name', models.CharField(default=b'vacio', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(default=b'vacio', max_length=255)),
                ('school_type', models.CharField(default=b'vacio', max_length=255)),
                ('school_name', models.CharField(default=b'vacio', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=b'vacio', max_length=255)),
                ('expires', models.CharField(default=b'-1', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(default=b'vacio', max_length=255)),
                ('fb_first_name', models.CharField(default=b'vacio', max_length=255)),
                ('fb_last_name', models.CharField(default=b'vacio', max_length=255)),
                ('fb_email', models.EmailField(default=b'vacio@gmail.com', max_length=255)),
                ('fb_birthday', models.DateField(default=datetime.date.today)),
                ('fb_name', models.CharField(default=b'vacio', max_length=255)),
                ('fb_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettoken.Location')),
                ('fb_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettoken.TokenInfo')),
            ],
        ),
    ]
